server:
  port: 8087
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: api-boss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-boss-user?characterEncoding=UTF-8&serverTimezone=GMT&2B8
    username: root
    password: 123456
  mail:
    username: 752869332@qq.com
    password: twggcmxvrquxbbgj
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465 #协议为SMTP是SSL端口号465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    password: Lz826826

#jwt配置
jwt:
  #颁发者
  issuer: sdu
  #秘钥
  secret: com.sdu
  #30分钟过期
  expiration: 30


logging:
  level:
    com.baomidou.mybatisplus: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: 0
      #配置mybatis plus 在更新时只更新非空和非NULL的字段
      update-strategy: not_empty
