server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-order?characterEncoding=UTF-8&serverTimezone=GMT&2B8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-order
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: Lz826826

logging:
  level:
    com.baomidou: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: 0
---
spring:
  profiles: 8089
server:
  port: 8089
---
spring:
  profiles: 8189
server:
  port: 8189
